### ISSUE TITLE
ANE for Android

### ISSUE THREAD

**Issue by fxdevGer** [mziwisky/bullet-ane#1]
Hi, 

Could you tell me if and when do you plan to release bullet-ane for Android?

Thank you.

Christian

**Comment by mziwisky** [comment]
I'm afraid I don't have any plans at this time -- I have very little Android dev experience and very little access to Android devices with which to test it -- but please feel free to tackle it yourself if you're comfortable with Android.  I'm happy to answer any questions you develop along the way.

**Comment by ringodotnl** [comment]
Great stuff, maybe we can work something out for the Android version, can you contact me ?
Cheers.

**Comment by fxdevGer** [comment]
Just a note, JMonkey uses the Native Bullet Physics. The performance is really nice :)

**Comment by mziwisky** [comment]
Forgot to close this... Android support added in 0adce3b460
